appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Uk3Y/23PmOOHZuY+AjQ9brFhyJvqA+5AY8ApW5+XE241rVnzaXz/2Ii7vMxE7zuBlmlhcpmkRewFAY7M7EvJuatW+86OiKGzde+icSjpm2nlulEOweoDASiR8j1vZF3lHPUIVSdDh5Z37oU5suOMsQBkJKfoFMgRJhmxfTSel4/YTbg0pfWnD6nKiVTiF1vQvsPfxfiWzF/10aEOyprD2u8rUpHg28OKCkrhWSHqd1fIFJEgXgd1BAW76MIQ+N12OI2t+7dzc8HJ6Cvow3PAw/zEexz6zkChSg2yPUhY+GeDeLjUAC3YKjPFfB0AnKIDXNOsEHxo0y903J+fsSbl1VB4bhiekYJnV0I9ZJv4mUndHHkzy1Hb8gj9ydPhLy8xpclQRuz+8Un+qDaTRAFVVcNUBEhOGT/D2/sotvmM3Ib8ssB4w4fb2i3xUnxmx43HO6G5sY7eTfdvW7khWOjkfagg+N4va5oMEsuPSIVumWCUTT7TetfkF7D4j3GzHeoxT48Mk6YFuGCjqitZLgH1QaEAAdcJ01BFtE4ndsl1oomq54urjFHI0JkuOmyFzilb2YJdE/IQag8dBQ6dlOmwmBhkB7BB9vB5nNlhj0wCt0q7NbzXEOP2aRMM+11R5Y1d925XxXIRQnhlOlQbvvo2Rm7dMxeDtyc8JVEM8ROuZdM=}
provider:
  win: azure
